import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { scriptURL } from "@/constants";
import ReduxProvider from "@/store/redux-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src={scriptURL} async />
      </head>

      <body className={inter.className}>{children}</body>
    </html>
  );
}
